### $\textbf{Complementary Notebook 1: NumPy Exercises}$ 


This notebook contains a set of optional NumPy exercises to help you get more comfortable with arrays and basic linear algebra. These exercises are not required for the lab session, but I highly encourage you to try them on your own if you would like extra practice. Feel free to work through them at your own pace.


---
#### $\textbf{Part 1. Python Basics}$


- **NumPy**: A powerful numerical computing library offering efficient data structures and methods for defining arrays and performing operations, including linear algebra, on these arrays. See __[here](https://python-programming.quantecon.org/numpy.html)__ for more descriptions and illustrations.

In this section, we will learn how to use NumPy to define arrays and perform basic linear algebra.  

---
##### $\textbf{1.1. Define arrays and basic operations}$


In [1]:
# 1. Import libraries.

import numpy as np
import matplotlib.pyplot as plt
from collections import namedtuple 

In [ ]:
# 2. Define arrays

# Define a 1D NumPy array (can represent a mathematical vector)
a1 = np.array([1, 2, 3, 4])

# x is a NumPy array; x.shape tells us its dimension
a1, a1.shape

# (4,) means “one-dimensional array with 4 elements” (not a column or row vector yet).
# row vector will show 1x4
# col vector will show 4x1

(array([1, 2, 3, 4]), (4,))

In [ ]:
# 3. Reshape arrays
a1.reshape(4,1)                       # a method: reshapes a1 from 1-dimensional object to 2-dimensional object. There are 4 elements
                                      # along the first dimension, but only 1 element in the second dimension. This is essentially a 
                                      # column vector.
# 4x1 col vector

a1.reshape(2,2) 
# 2x2 col vector

# but a1 still retains its orginal structure (doesnt change permanently)

array([[1, 2],
       [3, 4]])

In [5]:
# 4. Element-by-element operations
a1+10, a1**2

(array([11, 12, 13, 14]), array([ 1,  4,  9, 16]))

In [6]:
x = np.array(['1', '2', 'word'])
x

array(['1', '2', 'word'], dtype='<U4')

In [ ]:
# 5. Other examples of 1-dimensional arrays.

a2 = np.zeros(5)                      # generates an array of 5 zeros.
a3 = np.ones(5)                       # generates an array of 5 ones.
a4 = np.random.random(5)              # generates an array of 5 elements, where each element takes value from a uniform distribution.
a5 = np.random.randn(5)               # generates an array of 5 elements, where each element takes value from a standard Gaussian distribution.
a6 = np.linspace(0,5,10)              # generates an array of 10 elements with regularly spaced values from 0 to 5 (inclusive).
a7 = np.arange(0, 10, 0.2)            # generates an array with spacing of 0.2 in between values.

In [ ]:
a6
# from 0 to 5 inclusive, 10 elements, regularly spaced out

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
a7
# doesnt include 10, spaced 0.2 apart

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [10]:
a8 = np.arange(0, 10, 0.5)
a8 

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
a8 = np.ones(5) * 5
a8
# get array of 5 from array of 1

array([5., 5., 5., 5., 5.])

In [12]:
# 6. Define a 2D array (matrix)
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
A, A.shape

# A has 3 rows and 2 columns

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 (3, 2))

---
##### $\textbf{1.2. Simple linear algebra in NumPy}$
**1.2.1. Dot product and matrix multiplication**
- `@` is matrix multiplication.
- `np.dot` / `x @ y` gives dot products (for 1D arrays).

In [16]:
# Two 1D arrays (vectors)
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 5.0, 6.0])

# @ computes the dot product for 1D arrays
# This equals 1*4 + 2*5 + 3*6 = 32
dot = np.dot(x,y)
dot_xy = x @ y
dot
dot_xy

np.float64(32.0)

In [17]:
M = np.array([[4.0, 4.0],
              [5.0, 6.0]])
v = np.array([8.0, 9.0])

# Matrix–vector multiplication
M @ v

# This computes:
# [1  2] [10]   [1*10 + 2*20]   [ 50]
# [3  4] [20] = [3*10 + 4*20] = [110]

array([68., 94.])

**1.2.2. Solving a linear system**

Consider the follow system of equations:

\begin{align}
3x + 2y + z & = 4 \\
5x -5y + 4z & = 3 \\
6x +z & = 0
\end{align}

Then:

In [18]:
# Let's solve the above system.
# Ax = b
# A = [3 2 1
    #  5 -5 4
    #  6 0 1] 
#x = [x
#     y
#     z]
#b = [4
#     3
#     0]

A    = np.array([[3, 2, 1],[5,-5,4],[6,0,1]])
b    = np.array([4,3,0])
sol  = np.linalg.solve(A,b) #to get vector of x 
print(sol)

# Other method (not preferred, above one is stable)
# Equivalently, we can pre-multiply the inverse of A to b:
sol1 = np.linalg.inv(A)@b             # requires that matrix A is nonsingular.
print(sol1)

[-0.49056604  1.26415094  2.94339623]
[-0.49056604  1.26415094  2.94339623]
