### $\textbf{Complementary Notebook 1: NumPy Exercises}$ 


This notebook contains a set of optional NumPy exercises to help you get more comfortable with arrays and basic linear algebra. These exercises are not required for the lab session, but I highly encourage you to try them on your own if you would like extra practice. Feel free to work through them at your own pace.


---
#### $\textbf{Part 1. Python Basics}$


- **NumPy**: A powerful numerical computing library offering efficient data structures and methods for defining arrays and performing operations, including linear algebra, on these arrays. See __[here](https://python-programming.quantecon.org/numpy.html)__ for more descriptions and illustrations.

In this section, we will learn how to use NumPy to define arrays and perform basic linear algebra.  

---
##### $\textbf{1.1. Define arrays and basic operations}$


In [1]:
# 1. Import libraries.

import numpy as np
import matplotlib.pyplot as plt
from collections import namedtuple 

In [2]:
# 2. Define arrays

# Define a 1D NumPy array (can represent a mathematical vector)
a1 = np.array([1, 2, 3, 4])

# x is a NumPy array; x.shape tells us its dimension
a1, a1.shape

# (4,) means “one-dimensional array with 4 elements” (not a column or row vector yet).

(array([1, 2, 3, 4]), (4,))

In [3]:
# 3. Reshape arrays
a1.reshape(4,1)                       # a method: reshapes a1 from 1-dimensional object to 2-dimensional object. There are 4 elements
                                      # along the first dimension, but only 1 element in the second dimension. This is essentially a 
                                      # column vector.


array([[1],
       [2],
       [3],
       [4]])

In [4]:
# 4. Element-by-element operations
a1+10, a1**2

(array([11, 12, 13, 14]), array([ 1,  4,  9, 16], dtype=int32))

In [5]:
# 5. Other examples of 1-dimensional arrays.

a2 = np.zeros(5)                      # generates an array of 5 zeros.
a3 = np.ones(5)                       # generates an array of 5 ones.
a4 = np.random.random(5)              # generates an array of 5 elements, where each element takes value from a uniform distribution.
a5 = np.random.randn(5)               # generates an array of 5 elements, where each element takes value from a standard Gaussian distribution.
a6 = np.linspace(0,5,10)              # generates an array of 10 elements with regularly spaced values from 0 to 5 (inclusive).
a7 = np.arange(0, 10, 0.2)            # generates an array with spacing of 0.2 in between values.

In [6]:
# 6. Define a 2D array (matrix)
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
A, A.shape

# A has 3 rows and 2 columns

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 (3, 2))

---
##### $\textbf{1.2. Simple linear algebra in NumPy}$
**1.2.1. Dot product and matrix multiplication**
- `@` is matrix multiplication.
- `np.dot` / `x @ y` gives dot products (for 1D arrays).

In [7]:
# Two 1D arrays (vectors)
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 5.0, 6.0])

# @ computes the dot product for 1D arrays
# This equals 1*4 + 2*5 + 3*6 = 32
dot_xy = x @ y
dot_xy

32.0

In [8]:
M = np.array([[1.0, 2.0],
              [3.0, 4.0]])
v = np.array([10.0, 20.0])

# Matrix–vector multiplication
M @ v

# This computes:
# [1  2] [10]   [1*10 + 2*20]   [ 50]
# [3  4] [20] = [3*10 + 4*20] = [110]

array([ 50., 110.])

**1.2.2. Solving a linear system**

Consider the follow system of equations:

\begin{align}
3x + 2y + z & = 4 \\
5x -5y + 4z & = 3 \\
6x +z & = 0
\end{align}

Then:

In [9]:
# Let's solve the above system.

A    = np.array([[3, 2, 1],[5,-5,4],[6,0,1]])
b    = np.array([4,3,0])
sol  = np.linalg.solve(A,b)
print(sol)

# Equivalently, we can pre-multiply the inverse of A to b:
sol1 = np.linalg.inv(A)@b             # requires that matrix A is nonsingular.
print(sol1)

[-0.49056604  1.26415094  2.94339623]
[-0.49056604  1.26415094  2.94339623]
