### $\textbf{Homework 1}$

The problems in this document are about the material in the QuantEcon lecture __[Asset Pricing: Finite State Models](https://quantecon.github.io/2026-tom-course/markov_asset.html)__

Due date: January 26 (Monday)

<br>

**Exercise 1 (4 points)** 

* Please use the definition of a conditional covariance to deduce equation (1.4) from equation (1.2).

* Please explain how the random variable $m_{t+1}$ discounts payoffs in some states of the world and emphasizes payoffs in some other states of the world.

**Exercise 2 (4 points)**

* Please interpret equation (1.10) as the solution of a **functional equation**.  Please tell what function is determined by the equation.  Please explain how the equation represents that function as a vector.

* Please describe the dimensions of the $v$ and $K$.  

* Please explain how the dynamics of the growth rate of dividends influence the solution of the function determined by (1.10).  

* Please write one or two lines of Python code that solves functional equation (1.10). (*You may assume $K$, $\beta$, and $n$ are already defined.*)

**Exercise 3 (2 points)**

Please write a functional equation that you can use to determine the price of a consol as a function of a Markov state that governs  the stochastic discount factor. 


**Exercise 4 (2 points)**

Please write a functional equation that determines the price of a call option on a consol.  

**Exercise 5 (extra credit, 4 points):**

Please write Python code that can compute the price functions of the Markov state for exercises 3 and 4. Please include a short, runnable example. (*Your submission must run as written. Code that fails to execute will receive no credit.*)


**Exercise 1 (4 points)** 

* Please use the definition of a conditional covariance to deduce equation (1.4) from equation (1.2).

<a id='equation-lteeqs0'></a>
$$
p_t = {\mathbb E}_t \left[ m_{t+1}  ( d_{t+1} + p_{t+1} ) \right] \tag{1.2}
$$

<a id='equation-lteeqs101'></a>
$$
{\mathbb E}_t (x_{t+1} y_{t+1}) = {\rm cov}_t (x_{t+1}, y_{t+1}) + {\mathbb E}_t x_{t+1} {\mathbb E}_t y_{t+1} \tag{definition of conditional variance}
$$

replace $x_{t+1}$ with $m_{t+1}$ and $y_{t+1}$ with $d_{t+1}$ + $p_{t+1}$

<a id='equation-lteeqs102'></a>
$$
p_t = {\mathbb E}_t m_{t+1} {\mathbb E}_t (d_{t+1} + p_{t+1}) + {\rm cov}_t (m_{t+1}, d_{t+1}+ p_{t+1}) \tag{1.4}
$$

* Please explain how the random variable $m_{t+1}$ discounts payoffs in some states of the world and emphasizes payoffs in some other states of the world.

The covariance term captures the state-dependent component $m_{t+1}$ and would be 0 if $m_{t+1}$ were constant across states. But if $m_{t+1}$ is a random variable: if payoffs $d_{t+1}$ + $p_{t+1}$ is high and $m_{t+1}$ is high, covariance > 0 and price of asset would increase, thus emphasising payoffs in these states. Whereas if payoffs $d_{t+1}$ + $p_{t+1}$ is high and $m_{t+1}$ is low, covariance < 0 and price of asset would decrease, thus discounting payoffs in these states.



**Exercise 2 (4 points)**

* Please interpret equation (1.10) as the solution of a **functional equation**.  Please tell what function is determined by the equation.  Please explain how the equation represents that function as a vector.

The functional equation being determined is the **price–dividend ratio as a function of states $X_t$, $v(X_t)$**.


**Function that is unknown** and is being determined by the equation is $v(X_t)$, $v: \{x_1, x_2, ..., x_n\}$ --> R defined on finite states.

From the price-dividend ratio from (1.5)
<a id='equation-pdex'></a>
$$
v_t = {\mathbb E}_t \left[ m_{t+1} \frac{d_{t+1}}{d_t} (1 + v_{t+1}) \right] \tag{1.5}
$$

we integrate the function into the ratio by replacing $v_t$ with $v(X_t)$ to get the functional equation, which expresses how the function $v(X_t)$ depends on itself in future states.
$$
v(X_t) = \beta {\mathbb E}_t [ g(X_{t+1}) (1 + v(X_{t+1})) ]
$$

conditioning on $X_t = x_t$, we get
$$
v(x) = \beta \sum_{y \in S}  g(y) (1 + v(y)) P(x, y)
$$
which is like a weighted average, where we can rewrite it as


<a id='equation-pstack'></a>
$$
v(x) = \beta \sum_{y \in S}   K(x, y) (1 + v(y))
\quad \text{where} \quad
K(x, y) := g(y) P(x, y) \tag{1.8}
$$

And this is the **vector equation of R^n and function is represented as a finite-dimensional vector**.


Thus, this equation in 1.10 is the matrix inverse solution that satisfies the equations for all states.
<a id='equation-rned'></a>
$$
v = (I - \beta K)^{-1} \beta K{\mathbb 1} \tag{1.10}
$$


* Please describe the dimensions of the $v$ and $K$.  

Dimension of $v$ is $R ^{nx1}$, a column vector representing one entry per state.

Dimension of $K$ is $R ^{nxn}$. $K = g*P$ where g has the growth rates and P is the transition matrix containing the states. Both of these matrices have dimension $R ^{nxn}$, thus dimension of $K$ is $R ^{nxn}$

* Please explain how the dynamics of the growth rate of dividends influence the solution of the function determined by (1.10).  

When $g_i$ increases, the values in row i of matrix K increase (increase row-wise). With larger K values, there will be larger $v_i$. So high dividend growth today leads to higher expected future dividends, thus higher price-dividend ratio (solution of function).

* Please write one or two lines of Python code that solves functional equation (1.10). (*You may assume $K$, $\beta$, and $n$ are already defined.*)

In [2]:
import numpy as np
n = 2
beta = 1 / (1+0.04)
g = np.array([[1.01, 0],
              [0, 1.05]])
P = np.array([[0.9, 0.1],
              [0.2, 0.8]])
K = np.dot(g, P)
v = np.linalg.solve(np.eye(n) - beta * K, beta * K @ np.ones(n))
v

array([61.73346693, 70.07014028])

**Exercise 3 (2 points)**

Please write a functional equation that you can use to determine the price of a consol as a function of a Markov state that governs the stochastic discount factor. 

$$
p(X_t) = \beta {\mathbb E}_t [ g(X_{t+1})^{-\gamma} (\zeta + p(X_{t+1})) ]
$$

**Exercise 4 (2 points)**

Please write a functional equation that determines the price of a call option on a consol. 

$$
w(X_t, p_S)
= \max \left\{
    \beta \, {\mathbb E}_t g(X_{t+1})^{-\gamma} w(X_{t+1}, p_S), \;
         p(X_t) - p_S
\right\}
$$

**Exercise 5 (extra credit, 4 points):**

Please write Python code that can compute the price functions of the Markov state for exercises 3 and 4. Please include a short, runnable example. (*Your submission must run as written. Code that fails to execute will receive no credit.*)

In [4]:
import numpy as np

# -------------------------------
# Example setup
# -------------------------------

# Number of states
n = 3

# Markov state growth factors
g = np.array([1.02, 1.01, 0.98])  # g(X_{t+1})

# Transition probabilities (rows sum to 1)
P = np.array([
    [0.8, 0.15, 0.05],
    [0.2, 0.6, 0.2],
    [0.1, 0.2, 0.7]
])

# Parameters
beta = 0.95
gamma = 2.0
zeta = 1.0  # coupon of the consol
p_S = 2.5   # strike price for the call option

# -------------------------------
# Exercise 3: price of the consol
# -------------------------------

# Build K matrix: state-dependent discounting
K = P * g**(-gamma)  # element-wise multiplication row-wise

# Solve functional equation: p = beta * K * (zeta + p)
# Rearrange: (I - beta*K) p = beta*K*zeta*1
v_consol = np.linalg.solve(np.eye(n) - beta*K, beta*K * zeta @ np.ones(n))

print("Price of the consol in each state:")
print(v_consol)

# -------------------------------
# Exercise 4: price of a call option on the consol
# -------------------------------

# Initialize option price vector
w = np.zeros(n)
tol = 1e-8
max_iter = 1000

for it in range(max_iter):
    w_new = np.maximum(beta * K @ w, v_consol - p_S)  # functional equation
    if np.max(np.abs(w_new - w)) < tol:
        break
    w = w_new

print("\nPrice of the call option on the consol in each state:")
print(w)


Price of the consol in each state:
[14.91229615 16.06013806 17.30587927]

Price of the call option on the consol in each state:
[12.41229615 13.56013806 14.80587927]
